### ISSUE TITLE
Compatibility with Daredevil

### ISSUE THREAD

**Issue by doegox** [FdLSifu/qscat#2]
Hi, it would be nice to make qscat compatible with Daredevil format, this implies:

* be able to deal with a single file concatenating all traces (and a param to tell nr of samples & nr of traces), which is IMHO nicer than dealing with N files
* maybe be able to parse also input & output files, so if one chooses to save only part of the traces, the corresponding subset of inputs / outputs can be saved too

**Comment by FdLSifu** [comment]
Hi,
Initially, i have planned on updating daredevil to take "offset.bin" which contains shift offset for each curves. 
This is to avoid copying xGb, it is smarter to work with offset file which can be changed for each synchro. This is how I saw compatibility with DareDevil.

In mean time I'll solve #1 which will provide direct compatibility to Daredevil.

What do you think?

**Comment by doegox** [comment]
Yes it could be nice for daredevil to be able to take an offset table, maybe also with "selected" marks so you can tell to skip some specific traces.
But generally speaking this is also useful to rewrite the traces in case they need extra processing by third party tools without requiring each of them to understand offsets.
So both options are useful :)

**Comment by FdLSifu** [comment]
I have pushed support of opening single file containing several traces as suggested https://github.com/FdLSifu/qscat/commit/e88d8650b7d30074570fb9d44e95682d4f405150 

I will close this thread as text management will be treated in another issue
